import os
import requests
import streamlit as st
from components.diagnostics import render_diagnostics

BACKEND_URL = os.getenv("BACKEND_URL", "http://localhost:8000")
BACKEND_API_KEY = os.getenv("BACKEND_API_KEY", "")
REQUEST_HEADERS = {"X-API-Key": BACKEND_API_KEY} if BACKEND_API_KEY else {}


# ── Page Config ───────────────────────────────────────────
st.set_page_config(
    page_title="E-Commerce Search Engine",
    page_icon="🛍️",
    layout="wide",
)

# ── Header ────────────────────────────────────────────────
st.title("🛍️ E-Commerce Semantic Search")
st.caption("Powered by Hybrid Dense + Sparse Retrieval · Reciprocal Rank Fusion · LLM Generation")
st.divider()

# ── Session State Init ────────────────────────────────────
if "last_answer" not in st.session_state:
    st.session_state.last_answer = None
if "last_source" not in st.session_state:
    st.session_state.last_source = None
if "last_timing" not in st.session_state:
    st.session_state.last_timing = {}
if "last_products" not in st.session_state:
    st.session_state.last_products = []

# ── Search Input ──────────────────────────────────────────
query = st.text_input(
    label="Ask about a product",
    placeholder="e.g. waterproof hiking bag, wireless charger under $25...",
    max_chars=200,
)

search_clicked = st.button("Search", type="primary")

# ── Query Execution ───────────────────────────────────────
if search_clicked and query.strip():
    with st.spinner("Searching..."):
        try:
            response = requests.post(
                f"{BACKEND_URL}/api/v1/ask",
                json={"q": query.strip(), "limit": 5},
                headers=REQUEST_HEADERS,
                timeout=30,
            )
            response.raise_for_status()
            data = response.json()

            st.session_state.last_answer = data.get("answer", "")
            st.session_state.last_source = data.get("source", "llm")
            st.session_state.last_timing = data.get("timing", {})
            st.session_state.last_products = data.get("retrieved_products", [])

        except requests.exceptions.ConnectionError:
            st.error("Cannot connect to backend. Make sure the FastAPI server is running.")
        except requests.exceptions.Timeout:
            st.error("Request timed out. The LLM may be under load.")
        except Exception as e:
            st.error(f"Unexpected error: {e}")

elif search_clicked and not query.strip():
    st.warning("Please enter a search query.")

# ── Answer Display ────────────────────────────────────────
if st.session_state.last_answer:
    st.subheader("💬 Answer")

    source_badge = {
        "cache": "⚡ Served from Cache",
        "llm": "🤖 Generated by LLM",
        "llm_error": "⚠️ LLM Generation Failed",
        "no_results": "❌ No Results Found",
    }.get(st.session_state.last_source, "")

    st.caption(source_badge)

    st.markdown(
        f"""
        <div style="
            background-color: #1e1e2e;
            border-left: 4px solid #7c3aed;
            padding: 1.2rem 1.5rem;
            border-radius: 0.5rem;
            font-size: 1rem;
            line-height: 1.7;
            color: #e2e8f0;
        ">
            {st.session_state.last_answer}
        </div>
        """,
        unsafe_allow_html=True,
    )

# ── Diagnostics Sidebar ───────────────────────────────────
if st.session_state.last_timing:
    render_diagnostics(
        timing=st.session_state.last_timing,
        retrieved_products=st.session_state.last_products,
    )